### ISSUE TITLE
How to toggle 'notes-2.txt'

### ISSUE THREAD

**Issue by boudiccas** [rnkn/notes#3]
Exactly how do I toggle 'notes-2.txt' please? I've used the key setup that you showed in the last line of the 'readme.md', but haven't found out how to enable it in any shape or form. I've even looked at your config here on github (thanks for posting it btw) but you don't seem to have enabled it either. So how do I do it please?

**Comment by rnkn** [comment]
You're probably on the MELPA-stable version instead of the master branch that's shown in GitHub. You'll need to first set the option `side-notes-secondary-file` to a string (e.g. "notes-2.txt") for it to work. Alternately, wait a couple of days and I'll tag a stable release and then this will work by default.

**Comment by rnkn** [comment]
Alternately alternately, you can install via MELPA, which builds directly from the master branch. Let me know if you need any help doing that.

**Comment by boudiccas** [comment]
This is in my config file
```
(require 'side-notes)
(define-key (current-global-map) (kbd "M-s-n") #'side-notes-toggle-notes)
(setq side-notes-secondary-file "notes-2.txt")
```
But I still don't see how to call my secondary file. So how do I do it please?

**Comment by rnkn** [comment]
You gotta prefix with `C-u` i.e. `C-u M-s-n`.
